#on:
#  repository_dispatch:
#  workflow_dispatch:
#  push:
#    tags:
#      - "*"
#
#name: deploy
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#
#      - name: Docker login
#        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u nvr-ai --password-stdin
#
#      - name: Docker build
#        run: docker build --build-arg NPM_TOKEN=${{ secrets.GITHUB_TOKEN }} -t ghcr.io/${{ github.repository }}:${{github.ref_name}} .
#
#      - name: Docker push
#        run: docker push ghcr.io/${{ github.repository }}:${{github.ref_name}}
